version: '3'

services:
  icl_php-fpm:
    build:
      context: './'
    container_name: icl_php-fpm
    stdin_open: true
    tty: true
    volumes:
      - ./:/var/www
    networks:
      - icl
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_ROOT_USERNAME}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}

  icl_db:
    image: mariadb:10.6
    container_name: icl_db
    hostname: icl_db
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - icl-data:/var/lib/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    networks:
      - icl

  icl_nginx:
    image: nginx:alpine
    container_name: icl_nginx
    stdin_open: true
    tty: true
    ports:
      - "${APP_PORT:-80}:80"
      - "${APP_HTTPS_PORT:-443}:443"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - icl

volumes:
  icl-data:
    external: true

networks:
  icl:
    driver: bridge
